###
GET http://localhost:3000/api/v1/opennings

###
GET http://localhost:3000/api/v1/openning/?id=3

###
POST http://localhost:3000/api/v1/openning

{
    "role": "role",
    "company": "company",
    "location" : "location",
    "remote" : true,
    "link" : "link",
    "salary" : 10
}

###
PUT http://localhost:3000/api/v1/openning/?id=2

{
    "role": "role-udpate",
    "company": "company-udpate",
    "location" : "location-udpate",
    "remote" : false,
    "link" : "link-udpate",
    "salary" : 101
}

###
DELETE http://localhost:3000/api/v1/openning/?id=1